# 目录结构
source: ./src
# destination: ./blog #打包路径
# plugins:     ../_plugins
# layouts_dir:     ./_layouts
data_dir: ../_data
#collections: null

# 服务器选项
baseurl: ""

# 过滤
exclude: ['README.md', 'Rakefile']

#
sass:
  sass_dir: /blog/css
  style: compressed