# 目录结构
source: .
destination: ./blog #打包路径
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# 服务器选项
port: 4000
baseurl: /blog

# 过滤
exclude: ['README.md', 'Rakefile']